import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.FRANCHISE_CREATE,
    PERMISSIONS.FRANCHISE_VIEW,
    PERMISSIONS.FRANCHISE_UPDATE,
    PERMISSIONS.FRANCHISE_DELETE,
    PERMISSIONS.OUTLET_VIEW,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_MONITOR,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
  ],

  FRANCHISE_ADMIN: [
    PERMISSIONS.OUTLET_CREATE,
    PERMISSIONS.OUTLET_VIEW,
    PERMISSIONS.OUTLET_UPDATE,
    PERMISSIONS.OUTLET_DELETE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_CHANGE_ROLE,
    PERMISSIONS.USERS_CHANGE_STATUS,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.DEVICE_CREATE,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_UPDATE,
    PERMISSIONS.DEVICE_DELETE,
    PERMISSIONS.DEVICE_MONITOR,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
  ],

  OUTLET_MANAGER: [
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_UPDATE,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_UPDATE_STATUS,
  ],

  KITCHEN_STAFF: [
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.ORDERS_UPDATE_STATUS,
  PERMISSIONS.ORDERS_KITCHEN_VIEW, // add
],

PICKUP_STAFF: [
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.ORDERS_UPDATE_STATUS,
  PERMISSIONS.ORDERS_PICKUP_VIEW, // add
],
};
