import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ["*"],

  FRANCHISE_ADMIN: [
    PERMISSIONS.FRANCHISE_MANAGE,
    PERMISSIONS.OUTLET_MANAGE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
  ],

  OUTLET_MANAGER: [
    PERMISSIONS.MENU_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
  ],

  KITCHEN_STAFF: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_UPDATE_STATUS,
  ],

  PICKUP_STAFF: [
    PERMISSIONS.ORDERS_VIEW,
  ],
  KIOSK_DEVICE: [
  PERMISSIONS.ORDERS_CREATE
],
};
